---
title: 'HKS SUP-135 Project Part 2: Stories from the Opportunity Atlas'
author: "Matt Khinda"
date: "4/8/2023"
output: pdf_document
---

```{r setup, include=FALSE}
# Settings for PDF output
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE) 
knitr::opts_chunk$set(fig.width=12, fig.height=7, fig.align = "center") 

# Require packages and install and load if not already
if (!require(haven)) install.packages("haven"); library(haven)
if (!require(tidyverse)) install.packages("tidyverse"); library(tidyverse)
if (!require(ggplot2)) install.packages("ggplot2"); library(ggplot2)
if (!require(statar)) install.packages("statar"); library(statar)
if (!require(here)) install.packages("here"); library(here)
if (!require(htmltools)) install.packages("htmltools"); library(htmltools)
if (!require(sandwich)) install.packages("sandwich"); library(sandwich)
if (!require(lmtest)) install.packages("lmtest"); library(lmtest)
if (!require(sf)) install.packages("sf"); library(sf)
if (!require(ggspatial)) install.packages("ggspatial"); library(ggspatial)
if (!require(geojsonsf)) install.packages("geojsonsf"); library(geojsonsf)

# Clear workspace
rm(list=ls())
cat('\014')
```

```{r load data, include=FALSE}
atlas <- read_dta(here("datasets", "atlas.dta"))
streets <- read_sf(here("datasets", "Street_Centerlines_1999/Street_Centerlines_1999.shp"))
nodes <- read_sf(here("datasets", "Street_Centerlines_1999/Street_Nodes_1999.shp")) %>%
  select(OBJECTID) # removes all extraneous info
tract_geom <- read_sf(here("datasets", "Census_Tracts_in_2010/Census_Tracts_in_2010.shp")) %>%
  select(GEOID, geometry)
```

```{r map test}
# test plot to check that streets, nodes, and tracts are using the same coordinate projection system
ggplot()+
  geom_sf(data = tract_geom) +
  geom_sf(data = streets,  alpha = 0.5) +
  geom_sf(data = nodes, alpha = 0.5, size = 0.65) +
  theme_void()
```

```{r calc node degree}

# Example of loop calculating node degree
nodes_example <- nodes %>%
  subset(OBJECTID < 6) # limit example to first five nodes

for (i in seq(1, 5, 1)){
  # get list of binary variables for all road segments indicating if the segment touches the node
  touch_list <- st_touches(streets,nodes %>% subset(OBJECTID == i)) 
  # sum up count of 1s for roads that touch the node to obtain the node degree
  nodes_example$node_degree[i] <- sum(unlist(touch_list)) 
}


# DO NOT RE-RUN, TAKES 3+ HOURS! SEE ABOVE FOR DEMONSTRATION

# calculate avg nodal degree for each node in network 
  #for (i in seq(1, nrow(nodes), 1)){
    #touch_list <- st_touches(streets,nodes %>% subset(OBJECTID == i))
    #nodes$node_degree[i] <- sum(unlist(touch_list))
    
    # print progress
    #cat(paste0(round(i / nrow(nodes) * 100), '% completed'))
    #Sys.sleep(.5)
    #if (i == nrow(nodes)) cat(': Done')
    #else cat('\014')
  #}

# write data to geojson to avoid needing to re-run above loop in the future
  #st_write(nodes,here("datasets", "nodes_w_degree.geojson"))


# Replaces current dataframe with already prepared data including node degree
nodes <- geojson_sf(here("datasets", "nodes_w_degree.geojson"))

```

```{r group nodes by tract}

# assign each node to the tract it sits within and roll up by GEOID and calculate average node degree
tracts_w_node_degree <- st_join(tract_geom, nodes, join = st_contains) %>%
  group_by(GEOID) %>%
  summarise(avg_node_degree = mean(node_degree))

# plot map to visualize average node degree by tract
ggplot()+
  geom_sf(data = tracts_w_node_degree, aes(fill = avg_node_degree), color = NA) +
  scale_fill_viridis_c(option = "rocket") +
  geom_sf(data = streets,  alpha = 0.5, color = "white") +
  geom_sf(data = nodes, alpha = 0.5, size = 0.65, color = "white") +
  labs(fill = "Mean Nodal Degree", title = "Street Grid Connectedness (1999 Network) by Census Tract in Washington, DC") +
  annotation_scale(aes(unit_category = "imperial", style = "ticks"), tick_height = 0.6, pad_x = unit(1, "cm"), pad_y = unit(2, "cm")) +
  theme_void() +
  theme(plot.title = element_text(size=20,hjust = 0.5),
        legend.position = c(.9, .85),
        legend.justification = c("right", "top")) 
```

```{r join data to atlas}
# filter atlas data for DC only
DC_atlas <- subset(atlas, state == 11) 

# create new tract variable from full FIPS code and remove leading zeros to match atlas
tracts_w_node_degree <- tracts_w_node_degree %>%
  mutate(tract = sub("^0+", "", substr(GEOID, nchar(GEOID)-5, nchar(GEOID)))) %>%
  mutate(tract = as.numeric(tract))

# join average node degree value to atlas data by GEOID
DC_atlas <- left_join(DC_atlas, tracts_w_node_degree) %>%
  select(!c(GEOID, geometry))
```

```{r nodal degree summary stats}
# Get summary stats
sumStats_avgNodeDeg <- summary(DC_atlas$avg_node_degree)
# Add standard dev to summary stats
sumStats_avgNodeDeg["Std.Dev"] <- sd(DC_atlas$avg_node_degree, na.rm = T)

# convert summary stats to dataframe and rename variables
sumStats_avgNodeDeg <- data.frame(as.list(sumStats_avgNodeDeg)) %>%
  rename(Q1 = X1st.Qu.,
         Q3 = X3rd.Qu.)

sumStats_avgNodeDeg
```

```{r node degree histogram}
# histogram to explore distribution of mean nodal degree across tracts
ggplot(data = DC_atlas, aes(x = avg_node_degree))+
  geom_histogram(bins = 30, fill = "black", color = "white", size = 2) + 
  labs(title = "Distribution of Street Grid Connectedness (1999 Network) in Washington, DC", y = "Number of Census Tracts", x = "Mean Nodal Degree") + 
  theme_minimal() + 
  theme(plot.title = element_text(size=28,hjust = 0.5),
        text = element_text(size = 22),
        axis.text = element_text(size = 20)) 
```


```{r correlation test plot}
# scatterplot and linear regression line
ggplot(data = DC_atlas, aes(x = avg_node_degree , y = kfr_pooled_pooled_p25)) + 
  geom_point(size = 2) + 
  labs(title = "Street Grid Connectedness vs. Expected Income Percentile Rank for Children of Low-Income Parents in Washington, DC", x = "Mean Nodal Degree", y = "Income Percentile Rank at Age 35") +
  stat_smooth(method = "lm", se = FALSE) +
  theme_minimal() + 
  theme(plot.title = element_text(size=28,hjust = 0.5),
        text = element_text(size = 22),
        axis.text = element_text(size = 20)) 
```

```{r linear model}
univariate_model <- lm(kfr_pooled_pooled_p25 ~ avg_node_degree, data = DC_atlas)
summary(univariate_model)
```


```{r socioecon covariance testing}
# Socioeconomic measures
# Mean household income in 2000
ggplot(data = DC_atlas, aes(x = avg_node_degree , y = hhinc_mean2000)) + 
  geom_point(size = 2) + 
  labs(title = "Street Grid Connectedness vs. Mean Household Income (2000) in Washington, DC", x = "Mean Nodal Degree", y = "Mean Household Income in 2000") +
  stat_smooth(method = "lm", se = FALSE) +
  theme_minimal() + 
  theme(plot.title = element_text(size=28,hjust = 0.5),
        text = element_text(size = 22),
        axis.text = element_text(size = 20)) 

cor_coeff_meanInc_avgNodeDeg <- cor(DC_atlas$avg_node_degree, DC_atlas$hhinc_mean2000, use = "complete.obs")

# Single-parent household share in 2000
ggplot(data = DC_atlas, aes(x = avg_node_degree , y = singleparent_share2000)) + 
  geom_point(size = 2) + 
  labs(title = "Street Grid Connectedness vs. Share of Single-Parent Households (2000) in Washington, DC", x = "Mean Nodal Degree", y = "Fraction of Single-Parent Households in 2000") +
  stat_smooth(method = "lm", se = FALSE) +
  theme_minimal() + 
  theme(plot.title = element_text(size=28,hjust = 0.5),
        text = element_text(size = 22),
        axis.text = element_text(size = 20)) 

cor_coeff_singleParents_avgNodeDeg <- cor(DC_atlas$avg_node_degree, DC_atlas$singleparent_share2000, use = "complete.obs")

# Single-parent household share in 2000
ggplot(data = DC_atlas, aes(x = avg_node_degree , y = emp2000)) + 
  geom_point(size = 2) + 
  labs(title = "Street Grid Connectedness vs. Employment Rate (2000) in Washington, DC", x = "Mean Nodal Degree", y = "Employment Rate in 2000") +
  stat_smooth(method = "lm", se = FALSE) +
  theme_minimal() + 
  theme(plot.title = element_text(size=28,hjust = 0.5),
        text = element_text(size = 22),
        axis.text = element_text(size = 20)) 

cor_coeff_emp_avgNodeDeg <- cor(DC_atlas$avg_node_degree, DC_atlas$emp2000, use = "complete.obs")
```

```{r race covariance}
# Racial demographics
# Share of black residents
ggplot(data = DC_atlas, aes(x = avg_node_degree , y = share_black2000)) + 
  geom_point(size = 1) + 
  labs(title = "Street Grid Connectedness vs. Share of Black Residents in Washington, DC", x = "Mean Nodal Degree", y = "Share of Black Residents in 2000") +
  stat_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  theme(plot.title = element_text(size=28,hjust = 0.5),
        text = element_text(size = 22),
        axis.text = element_text(size = 20)) 

cor_coeff_Black_avgNodeDeg <- cor(DC_atlas$avg_node_degree, DC_atlas$share_black2000, use = "complete.obs")

# Share of white residents
ggplot(data = DC_atlas, aes(x = avg_node_degree , y = share_white2000)) + 
  geom_point(size = 1) + 
  labs(title = "Street Grid Connectedness vs. Share of White Residents in Washington, DC", x = "Mean Nodal Degree", y = "Share of White Residents in 2000") +
  stat_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  theme(plot.title = element_text(size=28,hjust = 0.5),
        text = element_text(size = 22),
        axis.text = element_text(size = 20)) 

cor_coeff_white_avgNodeDeg <- cor(DC_atlas$avg_node_degree, DC_atlas$share_white2000, use = "complete.obs")

# Share of Hispanic residents
ggplot(data = DC_atlas, aes(x = avg_node_degree , y = share_hisp2000)) + 
  geom_point(size = 1) + 
  labs(title = "Street Grid Connectedness vs. Share of Hispanic Residents in Washington, DC", x = "Mean Nodal Degree", y = "Share of Hispanic Residents in 2000") +
  stat_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  theme(plot.title = element_text(size=28,hjust = 0.5),
        text = element_text(size = 22),
        axis.text = element_text(size = 20)) 

cor_coeff_hisp_avgNodeDeg <- cor(DC_atlas$avg_node_degree, DC_atlas$share_hisp2000, use = "complete.obs")

# Share of asian residents
ggplot(data = DC_atlas, aes(x = avg_node_degree , y = share_asian2000)) + 
  geom_point(size = 1) + 
  labs(title = "Street Grid Connectedness vs. Share of Asian Residents in Washington, DC", x = "Mean Nodal Degree", y = "Share of Asian Residents in 2000") +
  stat_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  theme(plot.title = element_text(size=28,hjust = 0.5),
        text = element_text(size = 22),
        axis.text = element_text(size = 20)) 

cor_coeff_asian_avgNodeDeg <- cor(DC_atlas$avg_node_degree, DC_atlas$share_asian2000, use = "complete.obs")
```


```{r multivariate regression 1}
# Multivariate regression to control for socioecon factors only
multivariate_model_no_race <- lm(kfr_pooled_pooled_p25 ~ avg_node_degree 
                         + singleparent_share2000 
                         + emp2000, 
                         data = DC_atlas)

summary(multivariate_model_no_race)
```

```{r multivariate regression 2}
# Multivariate regression to control for socioecon factors and race
multivariate_model_race <- lm(kfr_pooled_pooled_p25 ~ avg_node_degree 
                         + singleparent_share2000 
                         + emp2000
                         + share_black2000
                         + share_white2000
                         + share_hisp2000
                         + share_asian2000, 
                         data = DC_atlas)

summary(multivariate_model_race)
```





